services:
  backend:
    image: saraabbas292/rag-law-backend:latest
    ports:
      - "7000:7000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - qdrant 

  frontend:
    image: saraabbas292/rag-law-frontend:latest
    ports:
      - "7070:80"
    depends_on:
      - backend

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage 

volumes:
  qdrant_storage:
